name: Generate Pac-Man Animation

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 错误在这里，已更正为正确的作者 ParthJain18
      - uses: ParthJain18/pacman-contribution-graph@v1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist # 输出目录

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
